export const TWEET_CHAR_LIMIT = 280;
export const URL_CHAR_COUNT = 23; // X counts all URLs as 23 characters
export const MAX_THREAD_ITEMS = 25;
export const MAX_IMAGES_PER_TWEET = 4;
export const MAX_IMAGE_SIZE_MB = 5;
export const MAX_VIDEO_SIZE_MB = 100;
export const MAX_POLL_OPTIONS = 4;
export const MIN_POLL_OPTIONS = 2;
export const POLL_OPTION_CHAR_LIMIT = 25;
export const PUBLISH_BATCH_SIZE = 10;
export const MAX_RETRY_COUNT = 3;
export const MIN_SCHEDULE_MINUTES_AHEAD = 5;
export const SWR_REFRESH_INTERVAL = 30000; // 30 seconds
export const AUTOSAVE_DEBOUNCE_MS = 3000;
export const NOTIFICATIONS_POLL_INTERVAL = 30000;
export const PAGE_SIZE = 20;

export const ACCEPTED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/gif", "image/webp"];
export const ACCEPTED_VIDEO_TYPES = ["video/mp4", "video/quicktime"];
export const ACCEPTED_MEDIA_TYPES = [...ACCEPTED_IMAGE_TYPES, ...ACCEPTED_VIDEO_TYPES];
